### ISSUE TITLE
+/- 45 degree pointing strategy for Leader/Follower

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#134]
**We might need to rethink (or at least think more) about docking approach angles (and also issues with magnets not pulling us together).**

```
adcs_vec1_current_f.set(r_hat_body_arr);
adcs_vec1_desired_f.set({1,0,0});
```

These two lines within attitude computer ask BOTH satellites to have their +X face Zenith. Since both satellites are physically identical, it's impossible for both Satellites to be docked and have both +X faces facing Zenith.

**EDIT:** If the satellites are docked, the +X faces will only be 90 degrees apart from one another.

Helpful link to images with axes:

Sats:
https://cornellprod-my.sharepoint.com/:x:/r/personal/saa243_cornell_edu/_layouts/15/Doc.aspx?sourcedoc=%7B4C5A75A0-8965-42FA-8FF0-1235E81EAF10%7D&file=mass_properties_calculations.xlsx&action=default&mobileredirect=true&wdLOR=c94C53D0A-1581-4725-ADF4-FE9C63DA5CEA&cid=3f32e25a-552c-459f-97bd-c5b2991f8ded

**Concerns:**

Approaching with both +X facing Zenith will ensure optimal iridium comms for both satellites, but the docking faces will be 90 degrees apart. This also means the magnets will exert **NO** attractive pull. ISL patches will also have 90 degrees of separation.

Approaching with 90 degrees of separation will allow the dimples of the docking face to contact perfectly, and also allow magnets to pull satellites together. ISL patches will be perfectly aligned with 0 degrees of separation. But Iridium patches will be 90 degrees offset, meaning both will be suboptimal, or one will be good and the other poor.

**Ideas:**

- Have both satellites +X faces 45 degrees offset from one another and approach optimally for docking but not for comms
- Have both +X target Zenith, we accept that they will approach not optimally set for docking, and then do something drastic once we get close.
- Can reconsider Peck's idea of a full dipole on satellite, but that means we'd have a dipole and we could smash together without dimples aligned.
- Approach with some variable offset (state field) to dynamically adjust (or at least tune infrequently) to dynamically compromise between iridium comms and magnet/docking alignment.

LMK if I messed anything up lol

_Originally posted by @shihaocao in https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/pull/120/files/ca4f9a623ba9f69455e6baa041bb9333143844c7_

**Comment by nhz2** [comment]
Won't the satellite's +X faces have to be 180 degrees apart when they are docked? I'm assuming the docking face on both leader and follower are the same, is one rotated, or could it be rotated 180 degrees?

**Comment by shihaocao** [comment]
@nhz2 
Since the "axis" of the actual blue docking piece is 45 degrees offset, it causes the X-axis to only be 90 degrees apart.

See this helpful diagram that Stewart drew:
https://prnt.sc/qk4iwu

Imagine both satellites are water bottles on tables, now flip across the dotted line as if you were turning one of the water bottles upside down. The docking face dimples will be perfectly aligned but the +X faces will be 90 degrees offset.

**Comment by nhz2** [comment]
Oh, that makes sense.

**Comment by shihaocao** [comment]
Prelim conclusion:
Choose option 1
> Have both satellites +X faces 45 degrees offset from one another and approach optimally for docking but not for iridium comms

To implement: Use offsets similarly for optimal solar, merely point a long edge towards zenith instead of the iridium patch location

**Comment by kkrol27** [comment]
Closing in favor of #287.
