### ISSUE TITLE
Magnetometer calibration task

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#139]
> Right now I am calibrating the magnetometer after eclipse, and after detumbling.

_Originally posted by @nhz2 in https://github.com/pathfinder-for-autonomous-navigation/psim/pull/92_

This needs to get implemented into FSW.

**Comment by shihaocao** [comment]
FSW:

- Monitor needs to set registers
- Controller needs timer to set modes into calibrate,
- Put a statefield to control timer, and offsets, independent for both

ADCS:

- Adjust readings based off of offset
- Implement calibrate for mag1
- Actually call calibrate in imu setup,
- And whenever mode is in calibrate

**Comment by tanishqaggarwal** [comment]
Sending to the backlog since #424 tracks the meat of the work. #424 is the science required prior to implementing this ticket.

**Comment by kylekrol** [comment]
Covered by #701 and #702.
