### ISSUE TITLE
Avoid busy waiting in the MMC34160 driver calibration.

### ISSUE THREAD

**Issue by nhz2** [pathfinder-for-autonomous-navigation/FlightSoftware#166]
Currently the calibrate function calls delay(50) a few times to wait for the set reset capacitor to charge. This should be handled in a way that avoids busy waiting for so long.

**Comment by tanishqaggarwal** [comment]
Preferably this is handled on the existing PR #164

**Comment by nhz2** [comment]
Kyle doesn't think this will break anything on ADCS, because the flight computer i2c requests are on interrupts. And those will still be handled during delay.

**Comment by tanishqaggarwal** [comment]
Let's close this issue then.
