### ISSUE TITLE
I2CDevice class is outdated

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#182]
I2CDevice currently sets is_functional to false if any five failures occur to I2C comms. I feel like this is not safe--with flight software having a robust architecture for managing faults now, I think we should strip I2CDevice's low-level is_functional setters.

@kkrol27 @shihaocao

**Comment by tanishqaggarwal** [comment]
Note: this only needs to be an FSW change. ADCS is probably fine?

**Comment by shihaocao** [comment]
Checked FSW, and could not locate such a bug. Closing for now, will reopen if rediscovered.
