### ISSUE TITLE
Breakout Magnetometers to Separate Registers

### ISSUE THREAD

**Issue by kkrol27** [pathfinder-for-autonomous-navigation/FlightSoftware#212]
Rather than having the ADCS box only read a single magnetometer at a time, it'll be more beneficial to have the ability to always read both magnetometers.

To support this, we'll change the I2C interface slightly, implement the change in ADCS software, and finally update FSW accordingly prior to merging.

**Comment by kkrol27** [comment]
See #213 for preliminary ADCS changes.

**Comment by shihaocao** [comment]
Resolved in PR #389
