### ISSUE TITLE
Attitude Controller

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#287]
For the sake of clarity, we'll merge the `AttitudeComputer` and `ADCSCommander` control tasks into a single control task named `AttitudeController`. In this process, we'll also integrate the controllers that have been incorporated into PSim (the detumbler and pointer controllers to be specific).

The main reasons for merging the control tasks tasks is to centralize all of the control logic for a given ADCS mode. Currently, the pointing objectives are determined in the `ADCSComputer` while the actual pointing happens in the `ADCSCommander`. This by itself makes sense except for the fact that not all ADCS modes require pointing objectives so sometimes the `ADCSComputer` is useless. Furthermore, many different ADCS modes use the same controller. This futhre makes the decentralization of attitude control difficult to follow.

In addition to merging the control tasks and integrating the controllers, we'll also need to make a small update to the current `AttitudeEstimator`. The finite differencing currently used to determine our angular rate is incredibly unreliable and we'll be moving to leveraging our gyroscope measurement in the future.

**Comment by kkrol27** [comment]
@shihaocao could you expand on which GNC functions we are referencing here?

**Comment by shihaocao** [comment]
I've actually got no idea what the names of them are but,
They are the functions that convert the desired vectors to actual MTR and Wheel commands.

**Comment by kkrol27** [comment]
Ahhh okay so stuff on top of the controller itself. We can talk about this this weekend and find the companion PSim tickets.

**Comment by kkrol27** [comment]
Just assigning myself too so I don't forget.

**Comment by kkrol27** [comment]
@shihaocao After talking with @tanishqaggarwal and @stewartaslan I'm just going to take this over for next week to take some stuff off your plate.

**Comment by kkrol27** [comment]
Per @nhz2 request, we'll also need to update documentation here in accordance with implementation: https://pan-software.readthedocs.io/en/latest/flight_software/components.html

**Comment by kkrol27** [comment]
The current pointing strategy defined in FSW needs to be reworked have the long edge of the satellite along the orbit normal and point the antenna phase outward at some angle `phi` specified in the hill frame.
