### ISSUE TITLE
Fix States Created and Consumed with Differing Underlying Types

### ISSUE THREAD

**Issue by kkrol27** [pathfinder-for-autonomous-navigation/FlightSoftware#337]
This was discovered while working on this [issue](https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/issues/305) and is well documented in this [PR](https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/pull/336).

Long story short, the new EEPROM controller assumes all of it's states will have an underlying types of `unsigned int` while some of those states (most notably `pan.state`, `pan.deployed`, and `pan.sat_designation`) are constructed with another underlying type.

The bug can be replicated locally as follows:

    git checkout kkrol/casts
    pio run -e fsw_native_leader
    python -m unittest --locals --buffer test/test_real_fsw.py

It's super helpful to edit lines `36-38` ish of `test/test_real_fsw.py` by adding in a print statement to dump response variable. Something like:

    def readCycleNumber(self):
        # Helper method to read the cycle count.

        input = json.dumps({"field": "pan.cycle_no", "mode" : ord('r')}) + "\n"
        self.console.write(input.encode())
        time.sleep(0.200)
        
        while self.console.in_waiting > 0:
            response = json.loads(self.console.readline().rstrip())

            print(response) # << Add in this

            if 'field' in response.keys():
                self.assertEqual(response['field'], "pan.cycle_no")
                return int(response['val'])

**Comment by tanishqaggarwal** [comment]
Being fixed in #331
