### ISSUE TITLE
Orbit Control Tasks

### ISSUE THREAD

**Issue by kylekrol** [pathfinder-for-autonomous-navigation/FlightSoftware#349]
We will have four primary orbit control tasks running on each spacecraft:

1. `TimeEstimator` The time estimator control task will be responsible for keeping track of the current absolute time estimate both in terms of GPS time and relative to the PAN epoch. This estimate must be considered valid for any downstream control tasks to operate.
2. `OrbitEstimator` The orbit estimator control task will be responsible for keeping track of the satellite's own orbit. It will run an EKF to produce position and velocity estimates in ECEF given GPS position and velocity measurements. If a control cycle misses a GPS measurement a prediction only step will be taken to given continuity to the estimate.
3. `OrbitPropegator` The orbit propagator control tasks will be responsible propagating orbital state estimates for the other spacecraft received from the ground to the current time. Once the propagation is complete, the estimate will be forwarded to the relative orbit estimator which will continue propagating the other spacecrafts orbital state in real time -- or ignore the data if CDGPS is available.
4. `RelativeOrbitEstimator` The relative orbit estimator will be responsible for providing the best estimate of the relative position and velocity of the other spacecraft given orbital uplinks and CDGPS information. This will be the most complicated of all the control tasks as it will most likely have to have a small state machine stood up internally.

A small diagram of the intended design is included below:

![orbit_control_tasks](https://user-images.githubusercontent.com/33558436/110385075-7bde1380-802c-11eb-94f9-fb91d05d7dfd.png)

See #655, #606, #607, and #656 for more details about each control task.

**Comment by tanishqaggarwal** [comment]
Assigning to Kyle and moving to backlog to represent that this is a low-priority item (though still the highest-priority backlogged item.)

**Comment by kylekrol** [comment]
#350 is getting brought into this ticket as well.
