### ISSUE TITLE
GPS/GNC Time Implementation

### ISSUE THREAD

**Issue by kylekrol** [pathfinder-for-autonomous-navigation/FlightSoftware#350]
We need to add a state field to provide time in seconds/nanoseconds since the "PAN epoch". This will be fed to many of the GNC algorithms and environmental models.

**Comment by shihaocao** [comment]
Still need this:

- Note that Piksi GPS time isn't a reading at "now" but rather a data point that's been in the buffer for a while
- Need a Kalman filter on the GPS time
- Increase uncertainty when GPS data isn't coming in, noise from Piksi
- If data becomes too uncertain (exceed a uncertainty threshold) or if we regress too far forward in time or behind when we suddenly get a new data point, this could be cause to either:
-- Reset everything,
-- Or apply a small delta t spread over many cycles to catch up, (wondering if this might mess up other estimations...)

**Comment by tanishqaggarwal** [comment]
Might as well make this part of the orbit estimator.

Note: shihao's comment above is out of date.
