### ISSUE TITLE
ADCS HAVT - GYR and SSA ADC#

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#354]
Sometimes, IMU GYR and ALL SSA ADC's report as non-functional.
More debugging is required.

**Comment by shihaocao** [comment]
Highly suspect this is because the MAG2 is down. Next steps: replace mag 2, and replicate behavior

**Comment by shihaocao** [comment]
Behavior to replicate: If either gomspace or the adcs_monitor or adcs_controller CT's are executing (and you cycle from ptest), the GYR and SSA ADC'S go down (seen in ADCS debug HAVT heartbeat)

**Comment by shihaocao** [comment]
We think there could be hardware EMI from Gomspace I2C and or FC to ADCSC I2C to Wire 2 on ADCSC (between all the SSA ADCS and IMU GYR)

**Comment by stewartaslan** [comment]
Cut the SCL and SDA traces to Mag 2 ([as-run procedure](https://cornellprod-my.sharepoint.com/:w:/r/personal/saa243_cornell_edu/_layouts/15/Doc.aspx?sourcedoc=%7B3c4c8faf-eeda-41be-a620-886a812627f8%7D&action=edit&wdPid=56966d08)). Everything passes on the ETU sat now.

<img width="839" alt="Screen Shot 2020-04-03 at 2 36 27 PM" src="https://user-images.githubusercontent.com/49573024/78400356-84c89880-75c4-11ea-905f-ef37acde31c8.png">
