### ISSUE TITLE
HOOTL slows down over long periods of time

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#378]
See the attached graph of pan.cycle_no, which increments almost logarithmically. Need to investigate this.
<img width="677" alt="Screen Shot 2020-04-05 at 11 49 53 AM" src="https://user-images.githubusercontent.com/5239500/78836233-b1632280-79bf-11ea-85c5-11ec3bc038f2.png">

**Comment by shihaocao** [comment]
Do you have the data points for this? Was thinking about checking it on log log plot

**Comment by kkrol27** [comment]
I'd look for some operations that `O(log n)` or `O(n log n)` where somehow `n` is directly related to number of cycle lmao This is pretty funny.

**Comment by tanishqaggarwal** [comment]
I think it came from here:
https://cornellprod-my.sharepoint.com/personal/saa243_cornell_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsaa243%5Fcornell%5Fedu%2FDocuments%2FOAAN%20Team%20Folder%2FSubsystems%2FSoftware%2FPull%20Request%20HITL%20Logs%2F%23359%20%2D%20Docking%20ptest%20checkout%20and%20DockingSystem%2BDockingController%20fixes%2FDockingCheckoutCase%5F20200331%2D155335

**Comment by kkrol27** [comment]
As in the log writing? How exactly is that handled?

**Comment by tanishqaggarwal** [comment]
I think I discovered the issue. TinyDB, the database that backs the incoming telemetry, is slow:

<img width="886" alt="Screen Shot 2020-04-20 at 11 21 27 AM" src="https://user-images.githubusercontent.com/5239500/79769304-f0677100-82f9-11ea-8ff9-35140bf7fb62.png">

This test runs 100,000 iterations of writing 100 values to the database.

Over time, as the database gets large, the insertion operation to the database has time complexity <img src="https://render.githubusercontent.com/render/math?math=O(n)">. Hence, the plot of time per control cycle vs control cycle # should be proportional to <img src="https://render.githubusercontent.com/render/math?math=n^2">, which is exactly the behavior we see.

I'll open a PR to add this stress test to the database, but I think we can consider this issue closed (unless we want to fix this issue somehow.)
