### ISSUE TITLE
assert(false) still fails on HITLs

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#383]
I noticed that assert(false) causes a hang on Teensy HITLs but not HOOTLs when the size of a flow was too large in a first draft of #371. This concerns me, because it's exactly the wrong behavior, and may persist through flight? We need to take a more careful look at the build flags.

**Comment by tanishqaggarwal** [comment]
We might have to put a custom assert into GNC, and then use it in FSW.

**Comment by athena255** [comment]
Adding ``${teensy.build_flags}`` to  line 15 to get rid of assert statements. fsw_native_leader does not call the assert statements either.

**Comment by athena255** [comment]
<img width="1016" alt="Screen Shot 2020-05-08 at 5 14 36 PM" src="https://user-images.githubusercontent.com/14916525/81451559-c9f76180-9152-11ea-872f-1bbde6d99b2d.png">
<img width="1018" alt="Screen Shot 2020-05-08 at 5 07 03 PM" src="https://user-images.githubusercontent.com/14916525/81451563-cc59bb80-9152-11ea-9945-c2f659e7f316.png">
