### ISSUE TITLE
Increase overflow safety of systime_t and systime_duration_t

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#395]
In #394 Fatima's implementing a set of functions to convert between systime and control cycle count. These functions aren't safe to the overflow of systime, so we should make systime and systime_duration better at managing overflow by increasing their size. Maybe by making them structs.

**Comment by athena255** [comment]
If systime and systime_duration are declared as uint64_t, I think that the arm compiler will create the logic needed to emulate a 64 bit variable (assuming 64 bit is all we need).

**Comment by tanishqaggarwal** [comment]
Let's make this a part of #350
