### ISSUE TITLE
Gyro heater integration into ADCS Software and Flight Software

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#409]
This never got done lmao

**Comment by shihaocao** [comment]
remove, p i d fields

**Comment by kkrol27** [comment]
Here is an old PR for reference: https://github.com/pathfinder-for-autonomous-navigation/ADCSSoftware/pull/15

* We're going implement a bang bang controller so we need to remove the `gyr_temp_p`, `gyr_temp_i`, and `gyr_temp_d` registers.
* Add a driver class for the heater and put another in device in the HAVT.
* Implement a bang bang controller in `imu.cpp`

**Comment by shihaocao** [comment]
![image (1)](https://user-images.githubusercontent.com/14984742/80343930-bedc3180-8834-11ea-83e7-720a3084d988.png)

weirdly low temps on the gyro_temp, investigating

**Comment by shihaocao** [comment]
above was performed on a minimal hitl

**Comment by shihaocao** [comment]
lol that took a lot more work than it was supposed to xd
