### ISSUE TITLE
If pressure sensor fails, then PropController will not be able to fire at all

### ISSUE THREAD

**Issue by athena255** [pathfinder-for-autonomous-navigation/FlightSoftware#422]
The current implementation in PropController relies on the pressure sensor. If the pressure sensor fails, then the PropController will not be able to tell when it should stop pressurizing. The state machine within the PropController requires that the pressure sensor report that the pressure in the outertank (Tank2) is above the threshold firing pressure (25 psi). If this is not the case, then the PropController will not be allowed to enter the Firing state.

**Comment by tanishqaggarwal** [comment]
The main concern behind this ticket is that this leaves us with no mechanism for manually controlling valves from the ground in the event that we want to investigate the issue from the ground. One proposed solution is to create a "safe manual" mode for PropController, which is like PropController's current manual mode, but actually enforces a 2 ms delay between valve openings and closes them after some specified duration. Thoughts @stewartaslan @kkrol27 ?

**Comment by tanishqaggarwal** [comment]
Implementation decision: instead of checking the pressure, we check the pressure _fault_. That way, the behavior to block entry to `firing` can be cleanly suppressed.
