### ISSUE TITLE
RWA Torque Reading (When wheels are saturated)

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#427]
What happens when the wheel is at max speed, and we command a torque that would saturate us? What should the torque reading say?

**Comment by nhz2** [comment]
I think the torque reading is directly from the analog reading of the potentiometer output, so it should still read the absolute value of the commanded torques, not the actual torques, if the wheels are saturated.

**Comment by shihaocao** [comment]
Right, but would anything bad happen to our controller code?

**Comment by shihaocao** [comment]
Resolved: Kyle said no, since we dont use torque reading for feedback.
