### ISSUE TITLE
Update files on remote server

### ISSUE THREAD

**Issue by fatimayousuf** [pathfinder-for-autonomous-navigation/FlightSoftware#439]
The remote server files need to be updated. 
- There shouldn't be a `main.py` file anymore (running `git pull` didn't change any of the files in gsw for me). 
- All the config files that are on the the .gitignore also need to be updated. 
- There sre no tlm or MCT folders. Again, running `git pull` didn't change anything for me.
- There exists both `/PAN/src/FlightSoftware/src/gsw` and `PAN/gsw`? We shouldn't need both...

I'm thinking maybe just re-clone the entire repository???

**Comment by tanishqaggarwal** [comment]
Recloning seems like the right thing to do. Go ahead.

The PAN/gsw is actually a symlink into PAN/FlightSoftware/src/gsw

**Comment by fatimayousuf** [comment]
Everything works! 😊
