### ISSUE TITLE
Rename fields inside AttitudeEstimator

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#445]
Not applicable to this review, but we should adjust this to `w_body_f` and `w_wheels_f`.

_Originally posted by @kkrol27 in https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/pull/435_

**Comment by kkrol27** [comment]
Thanks for making this! I'm going to link this in to the current attitude estimator issue!
