### ISSUE TITLE
Standardize state types

### ISSUE THREAD

**Issue by athena255** [pathfinder-for-autonomous-navigation/FlightSoftware#450]
State types of Control Tasks have been declared as unsigned int, unsigned char, char, etc. This causes issues with testing because `WritableStateField<unsigned char>*`  is not the same as `WritableStateField<unsigned int>*`. 

Idea: Typedef unsigned char as `STATE_T` and make all Control Task states of type STATE_T. 

An example of the issue is that QuakeManager declares "radio.state" as `InternalState<unsigned int>`, but many tests and control tasks that use radio.state expect an `InternalState<unsigned char>`. 

Since we do not serialize the enum states directly, they are cast into unsigned char, char,  or unsigned int when in the registry. If we declared a typedef of `STATE_T` we can also strongly type all the state enums as this type.

**Comment by kkrol27** [comment]
Is this only an issue with control tasks that don't return `void`? Would be easier to just remove the template argument for `ControlTask` and force all of them to return an integer code or char code even if it doesn't mean anything?

**Comment by tanishqaggarwal** [comment]
Almost certainly not going to have time to implement this.
