### ISSUE TITLE
RadioSession still sends JSON as uplink, not a compressed telemetry file

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#451]
Can't believe I didn't notice this before! We should fix this up

**Comment by tanishqaggarwal** [comment]
Maybe this can be made a part of #420 ? @afoarce

**Comment by afoarce** [comment]
> Maybe this can be made a part of #420 ? @afoarce

I can add it; how do we make the compressed file?

**Comment by tanishqaggarwal** [comment]
Check out `create_uplink` in state_session.py

**Comment by tanishqaggarwal** [comment]
It didn't take me that long to implement, so I'll just finish this one out
