### ISSUE TITLE
Gomspace driver issues

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#485]
Major issues exist with the Gomspace driver implementation and/or hardware configuration settings that prevent it from passing PTest cases and exhibiting desirable behavior.

Reference tickets:
#234 
#386

**Comment by tanishqaggarwal** [comment]
After testing today, we evaluated:
- A debug_console error causes counter values to be reported incorrectly.
- The hard reset command works as expected. Reboot doesn't seem to do anything, but hard reset does what we want it to (reset the entire spacecraft), so reboot doesn't matter.
- Unsure why PV voltages still don't change upon application. The plan is to see if the settings are correct on the flight units; if they are, we don't touch this function. If not, we have to scope out additional work to change the Gomspace Controller so that it can read/write config settings. We have to do this because the Gomspace USB terminal is not available on from the flight units.

**Comment by tanishqaggarwal** [comment]
#506 addressed most driver issues except for the PV voltage bug. We suspect possible ESD issues with the EDU gomspace due to a history of being poorly treated.

Paths forward: test with another Gomspace, test with flight units (dangerous). If the flight units don't permit the behavior either it may be time to look into expanding the GomspaceController to be able to write config values to the Gomspace.

**Comment by shihaocao** [comment]
The path forward is to just set GomSpace to default auto on the ground. We're going to ignore PV voltage setting problems.

For the best safety, satellites shall be charged when they are off.

**Comment by 18kudlugim** [comment]
<img width="1025" alt="Screen Shot 2021-02-20 at 3 01 08 PM" src="https://user-images.githubusercontent.com/32752995/108607167-bab56d80-738c-11eb-8efd-ebdb49a4f820.png">

**Comment by 18kudlugim** [comment]
Power cycling seems broken during gomspace hitl test. Is checking that all gomspace output channels are off at the same time an issue here?

**Comment by kylekrol** [comment]
Closed by #647.
