### ISSUE TITLE
HITL test the fault handlers

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#490]
Do after merging #479

**Comment by shihaocao** [comment]
PropFaultHandler PR fix on the way,
GomSpaceFaultHandler -> raise

**Comment by kylekrol** [comment]
I believe that this closes #502 as well?

**Comment by kylekrol** [comment]
@18kudlugim if we want to close this and add the HITL testing for the Piksi to the Piksi ticket itself I think we can do that.

**Comment by knk38** [comment]
Just to note, all fault handlers besides Piksi and Quake have been HITL tested at this point

**Comment by knk38** [comment]
Closing this as we have #652 for Quake and #694 for Piksi
