### ISSUE TITLE
SerializerTypes.inl constants for double vector and double quaternion

### ISSUE THREAD

**Issue by athena255** [pathfinder-for-autonomous-navigation/FlightSoftware#530]
https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/blob/f1abe2f1f52c6f6e2aa5c48ea2d464714d717734/src/common/SerializerTypes.inl#L714

The test_d_quat_serizlier test in test_serializer.cpp will fail if the constants dqsz, dvcsz, dqcsz are changed from 29, 9, 9 to 30, 10, 10 respectively. However, this test will pass if the constants are 40, 10, 10 (respectively). 

When changing the constants to 30, 10, 10, the test_serializer.cpp will fail on teensy 36 unit tests at line 662.The last element of the quat, which should have been 0.5 becomes negative. 

When changing to constants to 30, 30, 30, the unit tests will also fail and complain about nan.

**Comment by tanishqaggarwal** [comment]
Note: this may get closed by the `serializer_science` branch. I rewrote the entire vector serializer implementation so that it's simpler and works better.
