### ISSUE TITLE
Analyze timing performance of control tasks

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#532]
The timing behavior of control tasks hasn't been analyzed in a good long while. There may be some space for control cycle time optimization here and would be a good thing to do.

There are state fields that make this easy to do, see TimedControlTask.hpp.

If the control cycle timing can be optimized, be sure to change constants in all the places that it matters (psim, ptest, etc.)

**Comment by shihaocao** [comment]
We want to also check hardware dependencies, esp driver calls

**Comment by kylekrol** [comment]
Closing this in favor of #624.
