### ISSUE TITLE
Unit Vector Serializers

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#539]
Todo:
- Figure out what the magnitude bounds should be for a unit vector serializer? 0,1? 1,1? 1,2?
- Change the number of bits required for a unit vec serializer to be 0 + fvsc not 1 + fvsc
-- Update the serializers in FSW
-- Update the source code for serializers to be that way

**Comment by tanishqaggarwal** [comment]
- Fix up the sun sensor vector serializer
