### ISSUE TITLE
Gomspace PPT mode is not persistent across spacecraft reboots

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#547]
After doing some digging today on the flight units, I discovered that the Gomspace only respects the _hardware config_ setting of the PPT mode when the spacecraft is off. Changes made to the PPT mode via the I2C interface do not persist in the Gomspace's memory after the spacecraft turns off. This poses a problem because we absolutely need the Gomspace PPT mode to be "auto" when in flight even when the spacecraft is off, and for it to be "fixed" when on the ground when the spacecraft is off (so that we can charge via the barrel-jack connector.)

I think the right fix to this would be to create code that can use the I2C interface to change the Gomspace config settings for PPT mode. It doesn't necessarily need to be a part of the main Flight Software (it could be a separate, independent Arduino script), but it could use the existing configuration-changing functions inside the Gomspace driver to accomplish this.

**Comment by tanishqaggarwal** [comment]
A side effect of this work is that we also have to modify the ResetForFlight and PrepForCharging cases to edit the Gomspace configs, rather than setting the surface-level PPT mode.

**Comment by kylekrol** [comment]
This is actually now a non-issue. The hardware default PPT mode was set to MPPT over gosh. This means whenever booted the spacecraft will be in MPPT and we'll only charge it when the GOMSpace itself is off - i.e. the entire satellite is shutdown.

**Comment by tanishqaggarwal** [comment]
You might want to track removing PrepForCharging from the procedures.
