### ISSUE TITLE
Day-In-The-Life Testcase

### ISSUE THREAD

**Issue by kkrol27** [pathfinder-for-autonomous-navigation/FlightSoftware#555]
Given the duration the batteries lasted executing the reaction wheel stress test, we need a higher fidelity test to determine the health of our batteries.

Putting together a Day-In-The-Life (DITL) testcase seems to be the way to go. This new testcase will actuate the two most power hungry components in a flight like fashion:

 * Command the reaction wheel actuations based on old PSim data.
 * Broadcast the quake radio as frequently as if we're in orbit.

This testcase can be expanded upon in the future.

**Comment by tanishqaggarwal** [comment]
We scaled back the requirements on this testcase:
- We spin the wheels at [25, 10, 10] rad/s for 15 minutes, then ran down the battery to 7 V at a speed of [10, 10, 10]. This is a realistic-ish loading scenario for the wheels after a propulsion firing destabilizes attitude.
