### ISSUE TITLE
EEPROM Put vs Update

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#564]
EEPROM put doesn't call update if the `__arm__` flag is set
Pretty sure the above flag is true since teensy is arm.

`    template< typename T > const T &put( int idx, const T &t ){        
        const uint8_t *ptr = (const uint8_t*) &t;
#ifdef __arm__
        eeprom_write_block(ptr, (void *)idx, sizeof(T));
#else
        EEPtr e = idx;
        for( int count = sizeof(T) ; count ; --count, ++e )  (*e).update( *ptr++ );
#endif
        return t;
    }
};`

So, we either need to have our own smart writing, ie checking if the state field has changed and then writing, or modify the driver to do smart writing so we don't waste write cycles.

Or lastly, the most budget way, we just reduce our write cycles.

**Comment by kylekrol** [comment]
Hey @angelaloh09 @samuelqian01 did we end up closing this with a PR? If so we should link the PR on this ticket and then close it accordingly.
