### ISSUE TITLE
Attitude Controller Anomaly

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#565]
![image](https://user-images.githubusercontent.com/14984742/101292028-efc51180-37da-11eb-8ee6-587edb2f3fa6.png)

Dude what

**Comment by shihaocao** [comment]
![image](https://user-images.githubusercontent.com/14984742/101292092-606c2e00-37db-11eb-8df8-002aff1c750b.png)

**Comment by shihaocao** [comment]
![image](https://user-images.githubusercontent.com/14984742/101292115-7d086600-37db-11eb-8b07-6502c72135a9.png)

**Comment by tanishqaggarwal** [comment]
Bro what the

**Comment by shihaocao** [comment]
Should be solvable see SSA psim ticket

**Comment by tanishqaggarwal** [comment]
Closing due to duplicate issue in psim
