### ISSUE TITLE
Verify that all hardware checkout cases are still OK

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#573]
We should run them in HOOTL, EDU HITL, and finally both flight units.

**Comment by 18kudlugim** [comment]
<img width="851" alt="Screen Shot 2021-02-20 at 3 30 10 PM" src="https://user-images.githubusercontent.com/32752995/108608010-ea1aa900-7391-11eb-90fb-84d198a074b6.png">

**Comment by 18kudlugim** [comment]
DCDC Tests 2 and 4 had issues with resetting the pin. We expect ADCS pin to be true after reset but this doesn't seem to be happening.

**Comment by 18kudlugim** [comment]
<img width="1025" alt="Screen Shot 2021-02-20 at 3 01 08 PM" src="https://user-images.githubusercontent.com/32752995/108608039-2f3edb00-7392-11eb-913b-30c8fcc3260d.png">

Gomspace power cycling issues in hitl. Do we need all output channels to be off at the same time? #485

**Comment by 18kudlugim** [comment]
PiksiCheckoutCase and PropStateMachineCase look good in HITL. Haven't yet run ADCSCheckoutCase and SpinMotorsCase.

**Comment by knk38** [comment]
We got rid of SpinMotorsCase and verified that ADCSCheckoutCase works. Additionally we ran all other checkout cases in HITL. Fixes for Gomspace checkout and other cases that threw faults are in pr #647
