### ISSUE TITLE
log function implementation fix causes DownlinkProducer unit tests to fail

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#582]
The DownlinkProducer test data is dependent on an incorrect log function implementation, so it fails when the implementation is corrected. See failure log on #581

**Comment by tanishqaggarwal** [comment]
I forget if this bug causes log to return 1 minus the true value or 1 plus the true value. If it's 1 minus, it's a problem.

**Comment by tanishqaggarwal** [comment]
Will address as part of downlink auto-testing, #499

**Comment by kylekrol** [comment]
Hey @tanishqaggarwal did we end up cleaning this up?

**Comment by tanishqaggarwal** [comment]
No :(

**Comment by tanishqaggarwal** [comment]
There is a PR that fully addresses this issue but is semi-working on others: https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/pull/596/files

**Comment by kylekrol** [comment]
What's the implication of the bug? Is it critical?

**Comment by kylekrol** [comment]
Maybe we can talk about this briefly tomorrow as well

**Comment by tanishqaggarwal** [comment]
@kylekrol It could be critical, it affects the bitsizes of all downlinked fields.

The fix itself is quick (just look at the change in SerializerTypes.inl in the above PR). The problem is that we can't drop it in because it breaks the hardcoded downlink unit tests we currently have. Plus, making the change would require re-verification that any telemetry we're getting is correct. I have high confidence that it is (one purpose of the PR above is to show, on an automated test set, that the log2i fix works.) But I was unable to merge in the above PR because of segfaulting issues

**Comment by tanishqaggarwal** [comment]
The easiest way forward would be to make the change in SerializerTypes.inl, delete hardcoded unit tests for downlinks, and then do a manual verification that telemetry stuff still works. I hope this is easy enough, given that we've streamlined end-to-end testing quite a bit? I haven't actually attended a recent telemetry test so I'm not sure how easy this is.

**Comment by shihaocao** [comment]
Looks like serializers are working so "whatever" as things are still serializing properly.
