### ISSUE TITLE
Create state fields that would actually be used by Autonomous Mission Controller

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#586]
Currently the Autonomous Mission Controller is uploading data to orbit.baseline_pos, which is not great. It should instead be directly uploading its propagation of an orbit (along with a timestamp) to a spacecraft and allowing the spacecraft to make its own determination of the baseline position. We need to
- modify flight software to create these state fields
- modify AMC to use these state fields

**Comment by kylekrol** [comment]
Closing in favor of #349. There isn't really a point in fixing up an intermediate solution until the orbit propagator is integrated into flight software.
