### ISSUE TITLE
Update QuakeFaultHandler behavior to modify QuakeManager

### ISSUE THREAD

**Issue by 18kudlugim** [pathfinder-for-autonomous-navigation/FlightSoftware#590]
The current implementation is based on the assumption that the QuakeFaultHandler can only power cycle when the radio is in the Wait state.

After more examination, we determined that this underlying behavior needed to be changed. When the QuakeFaultHandler is about to power cycle, it should instead be setting the radio to be in the Wait state. This is related to the closed ticket #509 which tested this old behavior.

**Comment by kylekrol** [comment]
Hey @18kudlugim, did this end up getting taken care of by your previous PR?

**Comment by 18kudlugim** [comment]
> Hey @18kudlugim, did this end up getting taken care of by your previous PR?

yess
