### ISSUE TITLE
Allow RadioSessions to write to USBSessions

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#593]
In order to support HOOTL or Teensy-HITL-based AMC testing, (see test layout 4 [here](https://drive.google.com/file/d/1I-aAoazGzof-XElEN7QMVM5uXXUgvF1D/view?usp=sharing)), one possible implementation path would be to make the behavior of `write_state` RadioSession more configurable, so that it can switch between sending an email vs sending an HTTP request to the HTTP endpoint of a USBSession.

**Comment by shihaocao** [comment]
Closing per email scraper PR, accomplishes same thing with HIGHER fidelity
