### ISSUE TITLE
Ensure no memory leaks of FlightSoftware

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#604]
We should run FSW for a long, long time and check if memory usage keeps increasing.

**Comment by samuelqian01** [comment]
![Screenshot from 2021-04-17 10-30-30](https://user-images.githubusercontent.com/65980474/115117257-a6948380-9f6b-11eb-9ed5-a416ee85c001.png)
![Screenshot from 2021-04-17 10-35-44](https://user-images.githubusercontent.com/65980474/115117260-a8f6dd80-9f6b-11eb-8f75-af0308344e49.png)

No memory leaks after many many many hours of running.

**Comment by angelaloh09** [comment]
3 Hr Quake Test shows no memory leaks:
<img width="523" alt="Screen Shot 2021-05-08 at 10 18 58 AM" src="https://user-images.githubusercontent.com/44074422/117542486-d40ea300-afe6-11eb-970b-3ce8c6eb4783.png">

**Comment by angelaloh09** [comment]
70 min EduSat shows no memory leaks and normal cycling: (detumble state)

No Memory Leaks:
<img width="639" alt="pan_memory_use_ditl" src="https://user-images.githubusercontent.com/44074422/117542541-0f10d680-afe7-11eb-8c35-06f9957f4b2f.png">


Cycling: 
![pan_cycle_no_detumble_ditl](https://user-images.githubusercontent.com/44074422/117542519-f43e6200-afe6-11eb-896c-0498197992c5.png)
