### ISSUE TITLE
Check if we actually need to keep toggling DCDCs

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#605]
We might want to simplify a lot of logic (and remove the opportunity to make mistakes) by just removing the DCDC toggling. The only reason to toggle the DCDC is to save power. So in order to rest this concern, we should check if turning on the DCDCs actually causes a significant power draw by inspecting current draws from the Gomspace housekeeping packet.

**Comment by tanishqaggarwal** [comment]
If this happens, we might be able to close some existing tickets, such as #591

**Comment by knk38** [comment]
I think this issue can be closed as well since the SafeholdStandbyTransition case tests turning on the DCDCs and I did not observe a significant power draw when doing so. PR #631
