### ISSUE TITLE
[FSW] - I2C Driver Timeout

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#620]
Right now on, FSW I2C timeout to ADCS is set to 1000, presumably referencing to 1000ms which could cause interference with the proposed set CC time of 170 ms

**Comment by shihaocao** [comment]
Try to drop gomspace timeout to 1000 micros

**Comment by kylekrol** [comment]
This is the constant here that'd we want to move to 1000 micros instead of 10000:

    src/fsw/FCCode/Drivers/Gomspace.cpp:15: "gomspace_timeout" = "10000"

**Comment by kylekrol** [comment]
I went in to lab today and ran the GOMSpace checkout case with a lower GOMSpace i2c timeout of 1000 us but the driver failed to complete in time. Therefore, we're going to leave the timeout at 10,000 us.
