### ISSUE TITLE
Verification of control cycle times

### ISSUE THREAD

**Issue by knk38** [pathfinder-for-autonomous-navigation/FlightSoftware#624]
2 main issues:
-We need to verify control cycle times to make sure that they are not consistently late or displaying "cascading" lateness (where one task is late and causes all subsequent tasks to also be late)
-We need to make sure that the num_lates field in the timed control task is accurately counting the number of late tasks.

Some issues were observed when reading multiple gomspace state fields over a period of two minutes which causes an excessive number of tasks to be late in HITL. In HOOTL, the quantity of late tasks is lower but still consistently increasing which is a problem. Shown Below:

HITL:
<img width="530" alt="Screen Shot 2021-02-05 at 4 50 39 PM" src="https://user-images.githubusercontent.com/56562686/107092879-4bf3e400-67d2-11eb-851a-36aeedb8dbc3.png">

HOOTL:
<img width="512" alt="Screen Shot 2021-02-05 at 4 51 11 PM" src="https://user-images.githubusercontent.com/56562686/107092918-5d3cf080-67d2-11eb-8d51-a04cc79efad1.png">

These times were found after running the gomspace logger ptest case which just reads a collection of gomspace fields for two minutes. However, when running the Magnetorquer test case in HOOTL similar behavior was found, the difference is the late tasks weren't increasing, which is due to the nature of the test. 
<img width="512" alt="Screen Shot 2021-02-05 at 5 06 33 PM" src="https://user-images.githubusercontent.com/56562686/107094130-82caf980-67d4-11eb-8bb2-c741dbc0b758.png">

**Comment by knk38** [comment]
also related to #532

**Comment by shihaocao** [comment]
- Verify that if Flight Software is faster than 170 ms that we lower bound at 170 ms
- Add verifications to hardware checkout cases that every control task executes at 170ms
- Allocate debug task as much as we can up to letting everything sum to 170 ms
- Allocate for quake worst case (40k micros)? + gather more data
