### ISSUE TITLE
Mock modes for PTest x PSim

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#687]
Since FSW depends on Mode flags, ptest needs to translate Psim mode flags into settings for FSW

Mock piksi mode
"psim models RTK"

Mock HAVT table:
- gyro
- mag1 and/or mag2
- ssa "psim can disabled this"

**Comment by kylekrol** [comment]
This has been completed by the ptest restructuring pr!
