### ISSUE TITLE
ADCS Driver Questions

### ISSUE THREAD

**Issue by nhz2** [pathfinder-for-autonomous-navigation/FlightSoftware#69]
What are the units of the magnetorquer and wheel commands in the ADCS driver?

Also, how should the exponential filters coefficients be set to ignore all history?

**Comment by kkrol27** [comment]
Am^2 and torque in MKS.

**Comment by kkrol27** [comment]
On the adcs side at least that’s what the fixed point conversion is done with. However cuz it’s just a scale factor FSW can make it whatever you want (think @shihaocao used the same constants however so the units should be the same).

**Comment by kkrol27** [comment]
The exponential filter constants should be left to there defaults and you should be good to go.

**Comment by nhz2** [comment]
Is the speed command in rad/s ?

**Comment by kkrol27** [comment]
Oh forgot about that one, yep should be

**Comment by tanishqaggarwal** [comment]
Is this item closed?
