### ISSUE TITLE
Day-In-The-Life Test

### ISSUE THREAD

**Issue by kylekrol** [pathfinder-for-autonomous-navigation/FlightSoftware#695]
We want to run flight software for an extended period of time (on the order of a day or more) to verify flight software is actually stable enough - i.e. no subtle memory leaks and execution time remains constant over time.

This ideally would be run on an actual Teensy but we could think about running a long-duration HOOTL case as well if we monitor memory usage.

DITL Logging

24 Hr HOOTL

24 HR HITL QuakeBox

3 HR HITL EDU 

Relates to #604 and #624.

We may have issues with #557.

**Comment by shihaocao** [comment]
Want to track memory usage over Day in the Life, as well as cycles passed (indirect verification of timing)

**Comment by angelaloh09** [comment]
Goals of Ditl case were to fsw can run for long period of time, check for regular control cycle times & to ensure no memory leaks. 
- Verification of control cycle times with EDU 70 min. test attached in #624
- Verification of no memory leak plots/log screenshots for HOOTL Logging, 3HR Quake, and 70 min. Edusat attached in #604
