### ISSUE TITLE
GSW Close Out

### ISSUE THREAD

**Issue by knk38** [pathfinder-for-autonomous-navigation/FlightSoftware#804]
- Currently we have all of the layouts set up but they need to be completely filled out with bounds
- Widgets need to be set up as well
- Since we added new stuff to GSW lets update that on the docs

**Comment by Duncan-McD** [comment]
## Layouts:

 - Meeting must be made to decide what "Green" bounds are for important telem fields (particularly ones with widgets)
 - We also should, as an additional feature, come up with a formula for the mission status as a whole (Ex. Whether everything important is "Green") Which would allow us to have a front page to MCT/GSW with a Green or Red indicator light to indicated if each satellite is nominal. (This is not as critical as other widgets but would make our live's more convenient in end)
 - After meeting I can update the layout json using the OpenMCT editor/GUI

 #### Files needed to be changed:
 1. spreadsheet to organize bounds
 2. Layout .json file

 ## Documentation:

 - All the new procedures for ground software should be added to the documentation. 
 These Should include both:
  1.  user-end procedures 
   - How to import layout json files
   - how to login to MCT from browser
   - Until browser security/SSL/HSTS issues are fixed, add procedures to complete a bypass
  2. Server-end procedures
   - How to start up each piece of the server stack
   - How to diagnose server issues on scaleway end
   - Once the scripts are made to ease up server procedures, update this as well.
   
 #### Files needed to be changed:
 1. GSW ReadMe's
 2. Relevent Pprocs/Documentation
