### ISSUE TITLE
Verify Relative Orbit Estimator Can be Initialized in Far Field

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#810]
@govindchari reports that we don't have the relative orbit estimator initialized in far-field (follower only) mode.

Perhaps this is HITL only. Verification task as PTest case for this does exist in HOOTL.

**Comment by samuelqian01** [comment]
<img width="564" alt="Screen Shot 2021-09-25 at 12 43 27 PM" src="https://user-images.githubusercontent.com/65980474/134779550-9a763db9-153f-4ca4-a534-7929be82298a.png">
