### ISSUE TITLE
Pan Epoch Internal State Field Creation

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#92]
We/Shihao need/needs to figure out where (which control task) to create/define the Pan Epoch Internal State Field because the state field is necessary for gnc/attitude estimation calculations. The Pan Epoch Internal Statefield should be a gps_time_t.

**Comment by nhz2** [comment]
The actual value of Pan Epoch is in psim, in `include/gnc_constants.hpp` its called `gnc::constant::init_gps_week_number` to convert to nanoseconds, just cast to a int64_t and then multiply by (7L * 24L * 60L * 60L * 1000L * 1000L * 1000L), 
@kkrol27  maybe the nanoseconds version should be another constant in psim?

**Comment by shihaocao** [comment]
Resolved by defining pan_epoch is not a state field at all, and instead, as a constant pulled from gnc_constants
